### ISSUE TITLE
Create WasmEdge HTTP server sidecars

### ISSUE THREAD

**Issue by juntao** [second-state/dapr-wasm#17]
We would like to create two sidecars that are just `wasmedge` or `wasmedge-tensorflow-lite`. Instead of using GO or Rust to implement HTTP servers and then bootstrap wasmedge, we would just run those wasmedge-based server apps in sidecars. 

Sidecar #1: implement the grayscale function in Rust.

https://github.com/second-state/wasmedge_wasi_socket/tree/main/examples/http_server

Sidecar #2: implement the tensorflow function in JS

https://github.com/second-state/wasmedge-quickjs#http-request

https://github.com/second-state/wasmedge-quickjs#tensorflow

https://www.secondstate.io/articles/embed-javascript-in-rust/

After that, modify the web port to  show all 4 sidecar apps.

**Comment by chenyukang** [comment]
```
Sidecar #1: implement the grayscale function in Rust.

https://github.com/second-state/wasmedge_wasi_socket/tree/main/examples/http_server
```

Use wasi_socket to accept image data and then the grayscale is as before?

**Comment by juntao** [comment]
Great. Thanks. 

Re 1: Where did this "max bytes limit exceeded" error message come from? Is it from Dapr? WasmEdge? Or our function in WasmEdge?

Re 2: Is there a way for Dapr to auto restart services? If so, I think we could exit when there is an problem, and let Dapr restart the process?
