### ISSUE TITLE
Create a customized WasmEdge for dapr

### ISSUE THREAD

**Issue by juntao** [second-state/dapr-wasm#18]
The WasmEdge GO SDK allows developers to register host functions to the runtime, and create a customized version of WasmEdge that includes the host functions. 

We should add Dapr GO SDK functions into a customized version of WasmEdge.

We should then create Rust APIs for those Dapr host functions so that WasmEdge app developers can use them.

**Comment by Taction** [comment]
Very glad and looking forward to seeing it!

I am also interested in combining dapr with wasm, and am now a newbie to wasm. I am more familiar with dapr, whoever is in charge of this work can contact me, I am very happy and willing to build together or provide help if needed.

Besides, and it's just my personal opinion, I think there may be various ABI standards for different purposes. If the extension of abi is plug-in, it can be very convenient for others to extend their own abi based on your project.
![image](https://user-images.githubusercontent.com/13532065/137621645-221eb457-8b83-4f92-b51d-bedaf257d62c.png)
