### ISSUE TITLE
Use wasmedge-bindgen instead of wasm-bindgen in the GO SDK example

### ISSUE THREAD

**Issue by juntao** [second-state/dapr-wasm#27]
The current example uses `wasm-bindgen` to pass call parameters from the GO app to the WASM function. However, `wasm-bindgen` does not work with the Rust WASI target since Rust version 1.51. We now have a better solution for bindgen since WasmEdge 0.9.0. It is called `wasmedge-bindgen`:

https://wasmedge.org/book/en/embed/go/function.html

Can we refactor the GO host example to use `wasmedge-bindgen`?

**Comment by chenyukang** [comment]
@juntao 
I add some trivial fix on the branch.
Please have a Review for the PR.

**Comment by chenyukang** [comment]
em, there is an issue when I run the code:

```console
== APP == 2022/01/25 16:08:51 http: panic serving 127.0.0.1:41106: runtime error: index out of range [0] with length 0
== APP == goroutine 11 [running]:
== APP == net/http.(*conn).serve.func1()
== APP ==       /usr/local/go/src/net/http/server.go:1801 +0xb9
== APP == panic({0x662140, 0xc0000b0120})
== APP ==       /usr/local/go/src/runtime/panic.go:1047 +0x266
== APP == main.imageHandlerWASI({0x7fe2f4f67038, 0xc0000a8340}, 0xc0000ac2a0)
== APP ==       /home/coder/dapr-wasm/image-api-go/image_api.go:59 +0x65c
== APP == github.com/dapr/go-sdk/service/http.(*Server).AddServiceInvocationHandler.func1({0x6d0ac0, 0xc0000be1c0}, 0xc000092300)
== APP ==       /home/coder/go/pkg/mod/github.com/dapr/go-sdk@v1.2.0/service/http/invoke.go:46 +0x18a
== APP == net/http.HandlerFunc.ServeHTTP(0x800, {0x6d0ac0, 0xc0000be1c0}, 0x0)
== APP ==       /usr/local/go/src/net/http/server.go:2046 +0x2f
== APP == github.com/dapr/go-sdk/service/http.optionsHandler.func1({0x6d0ac0, 0xc0000be1c0}, 0x0)
== APP ==       /home/coder/go/pkg/mod/github.com/dapr/go-sdk@v1.2.0/service/http/service.go:65 +0x62
== APP == net/http.HandlerFunc.ServeHTTP(0x0, {0x6d0ac0, 0xc0000be1c0}, 0xc0000be1c0)
== APP ==       /usr/local/go/src/net/http/server.go:2046 +0x2f
== APP == net/http.(*ServeMux).ServeHTTP(0x0, {0x6d0ac0, 0xc0000be1c0}, 0xc000092300)
== APP ==       /usr/local/go/src/net/http/server.go:2424 +0x149
== APP == net/http.serverHandler.ServeHTTP({0x6d0008}, {0x6d0ac0, 0xc0000be1c0}, 0xc000092300)
== APP ==       /usr/local/go/src/net/http/server.go:2878 +0x43b
== APP == net/http.(*conn).serve(0xc000104b40, {0x6d1bc0, 0xc000074e70})
== APP ==       /usr/local/go/src/net/http/server.go:1929 +0xb08
== APP == created by net/http.(*Server).Serve
== APP ==       /usr/local/go/src/net/http/server.go:3033 +0x4e8
```

**Comment by chenyukang** [comment]
There is an error happened in https://github.com/second-state/dapr-wasm/blob/wasmedge-bindgen/image-api-go/image_api.go#L55

@wangshishuo

**Comment by wangshishuo** [comment]
I noticed that you have remove the import here:
https://github.com/second-state/dapr-wasm/commit/78051462be895bff70b57b70abf74533614eed6f#diff-0d6698a7aba3ca9ff2d9eab013e7826b88fe5f5c54e4d0d181bc936d5409196aL1

But you must keep it to make its exporing function to be in the export module in the wasm.

**Comment by chenyukang** [comment]
> @chenyukang I noticed that you have removed the import here: [7805146#diff-0d6698a7aba3ca9ff2d9eab013e7826b88fe5f5c54e4d0d181bc936d5409196aL1](https://github.com/second-state/dapr-wasm/commit/78051462be895bff70b57b70abf74533614eed6f#diff-0d6698a7aba3ca9ff2d9eab013e7826b88fe5f5c54e4d0d181bc936d5409196aL1)
> 
> But you must keep it to make its exporting function to be in the export module in the wasm.

That's the root cause!
Thanks!
Fixed it.
