### ISSUE TITLE
live demo is down?

### ISSUE THREAD

**Issue by katopz** [second-state/dapr-wasm#28]
http://23.100.38.125/static/home.html

Didn't seem to load for me. 🤔

**Comment by barakplasma** [comment]
Same getting 404 on http and https.
The server seems up since http://23.100.38.125/ gives us the nginx 404 page

**Comment by alabulei1** [comment]
@chenyukang Could you help check this out?

**Comment by chenyukang** [comment]
@barakplasma @katopz 
The live url is:
http://23.100.38.125:9000/static/home.html

**Comment by katopz** [comment]
Thanks, fixed https://github.com/second-state/dapr-wasm/commit/02f91a05f7bd6916a5de621939e606d753399a26
