### ISSUE TITLE
GitHub Pages

### ISSUE THREAD

**Issue by juntao** [second-state/dapr-wasm#45]
I have configured GitHub Pages to serve from the `main` branch's root directory. So, our static web page is now available here:

https://second-state.github.io/dapr-wasm/web/

We do not actually need a GitHub Action for this. As soon as we update the `main` branch, it will be automatically deployed. 

We could, however, to use GitHub Actions to copy just the `/web` folder to another branch (e.g., `gh-pages`) and then deploy the `gh-pages` branch as the web site's root.

**Comment by juntao** [comment]
Perhaps an easy way is just to rename the `web` folder to `docs`. GitHub Page allows setting `docs` as root.

Then we do not need any GitHub Actions at all. ;)

**Comment by chenyukang** [comment]
We can specifiy the root directory for Pages:
https://github.com/chenyukang/dapr-wasm/blob/main/.github/workflows/pages.yml#L38

My local repo tested OK.

**Comment by juntao** [comment]
I am not really sure which branch this action uploads to. Normally, you need the gh-pages branch.

But I think our problems can be simply solved by renaming web to docs on the main branch. ;)

**Comment by chenyukang** [comment]
Rename `web` to `docs` in https://github.com/second-state/dapr-wasm/pull/47.
