### ISSUE TITLE
Image formats

### ISSUE THREAD

**Issue by juntao** [second-state/dapr-wasm#48]
The `grayscale` service only supports the GIF and PNG formats. But the `classify` service only supports the JPG format. Can we make them consistent? 

Perhaps supports JPGs by default in both services? Thanks.

**Comment by chenyukang** [comment]
we don't have this limits, when the size of picture is large, `grayscale` will take long time.
I will try to `AOT` to make it faster.

**Comment by chenyukang** [comment]
Now, it's much faster, if you have any image don't work, please send me.

**Comment by juntao** [comment]
Do you mean that the grayscale service supports JPG as well?

**Comment by chenyukang** [comment]
> Do you mean that the grayscale service supports JPG as well?

yes, I tested with several JPG as well.
